mergeable:
  pull_requests:
    # Regular expression to be tested on the title. Not mergeable when true.
    title:
      begins_with:
        match: '(feat)|(chore)|(fix)'
        message: 'Title must begin with fix, feat or chore'