language: node_js
node_js:
- 10.10.0
dist: trusty
git:
  depth: false
jobs:
  include:
    - stage: "Fundamental-react: Lint"
      script: npm run build
deploy:
- provider: script
  script: build/public_rc.sh
  on:
    branch: master
- provider: script
  script: build/publish.sh
  on:
    tags: /^v\d+\.\d+\.\d+$/
