language: node_js
node_js:
- 10.10.0
dist: trusty
git:
  depth: false
jobs:
  include:
  - stage: Fundamental-react build
    name: Unit tests
    script: bash ./ci-scripts/unit-tests.sh
notifications:
  email:
    on_failure: always
    on_success: change
before_deploy:
- npm run build
deploy:
  provider: script
  script: bash ./ci-scripts/publish.sh $TRAVIS_BRANCH $TRAVIS_BUILD_NUMBER
  on:
    branch: master
  api:
    secure: AKVw7lhdfpo8dj0gC0E8vY3yrcparxSI/Y+g2hCHIseNScpsLbFYFRVK7UOMndIlgyrpm84hz/eQ6uP9lGk9nKLnhRZDt+b7ISgQdky119JGidHZjT4WLY5eSqpVtvBrWZt66nN7vDJM/D9b3O7aTCmxVyV702tzwVEC3Iy9MM/rntMLyqicxZzO3JLEchCU6i6WQQSOK/lHyiQygESsChSd3e9hqoE4OZsQGhn3QvkYSGCd4dZuvPYqMze4ea1VsEzvXp4W45STpefDB3qiek1JHiCClMS4iXI9gHmpu7+tOyg8lBSN0B6JHZ3o6a6ouY5EPI9XriHrY0rMTQwSOSMM5YbJdg88tnaVXWYOyoJx6SWMTtTsJ7BFYZc77+8Qk7u5g/oh6CJ5tVQ61o4hkos7TzhtkQz+WLgql5AGEkT4cgNZno9dHpyD2WBjE8fprsNoGWjIQDoPkSXOByLHAqLisf6f3uZ5iX9wT/USSqCDh/trgB0UCXz8LGgh6HGzH16q3XYN9qwK23HnxbhoZ3PQQxKKbBss3aphC4OuUUVjsJu5bGQZ1heoHfRdhH3l4Sp38KcWTzMb2BkPvZBGKbOOrbEQcltnByrDf4hAbtkyql4amoRYUHfmWh2J700lRh2i4oP94BMQzRjQETOtz0zNUjG20EIT4Vv/4SRhW1c=
  api_key:
    secure: u3ToNx/P7f72egYHYUmR1EHaD4XM/QpM55E9bQxtdBBKcASO0cPKN4Nk1h3GqPTLC4+nxNEtKdk2bHjggoYcQsPaxR0IrMvOEk9qPo83IG8oGkSXJE1KZUGUqnm6HVEgOaTf04+Cvk97AN7lv+Za0AwXxvldCkbHx/I/anNTrqC+qhriXEa8FMfVCDNDEb9p0f6DCdG2ELv9GUeKHDfL3UQ3FuaG/ob6D+QPZefcgikKjW+PxR8/auaNpHEf/E+stApNDWDJVUw4bzrJCsby94rki+kFoG+1LP7AJNLo6iBj7NVXQb/t4wiBD3b6QMuu8iPA3bbWJBqbbNmJLK1BYwBQQl2XYITv/RJ7dBN+3noysuH1Fy2UCtv2F+6ZDTdNoFvm+pUbvFFxIXru1F9h6NliK84laQ7LxqnK6Z46xZvsfrAYv3YCGnS7guWzQrxskb20/zjFwq0DoaPHJoYGQSoRY86NdM3YQlTxqepNFqS7fFutgsnvdL6LCiRXH/fZgYdfx/LLeouP4u/Kbx0j8BjVlZOg348NITeUUN1ggf/M7Lb7Qd+vdsKh057J4/VHUGWMe4itNWF/ytqtEZ2GECT++yWwVfM+OJhqsvNLZwGsB14fMYxtSaiPeBx8GOYF5Seta6G6aYgjZ5oRrnvzHQ2rH+ROglL6XkyhMJO3ikM=
